version: "3.8"
services:
  # HDFS & YARN
  namenode:
    image: apache/hadoop:3.3.6
    hostname: namenode
    container_name: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
      - 8020:8020
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    volumes:
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./config/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
      - ./config/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
      - ./config/capacity-scheduler.xml:/opt/hadoop/etc/hadoop/capacity-scheduler.xml
    networks:
      - bigdata

  datanode1:
    image: apache/hadoop:3.3.6
    hostname: datanode1
    command: ["hdfs", "datanode"]
    volumes:
      - ./config:/opt/hadoop/etc/hadoop/
    networks:
      - bigdata

  resourcemanager:
    image: apache/hadoop:3.3.6
    hostname: resourcemanager
    container_name: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    volumes:
      - ./config:/opt/hadoop/etc/hadoop/
    networks:
      - bigdata

  nodemanager:
    image: apache/hadoop:3.3.6
    hostname: nodemanager
    command: ["yarn", "nodemanager"]
    volumes:
      - ./config:/opt/hadoop/etc/hadoop/
    networks:
      - bigdata

  # PostgreSQL pour Hive Metastore
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: metastore_db
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - hive-db:/var/lib/postgresql/data
    networks:
      - bigdata

  # Hive Metastore
  metastore:
    image: apache/hive:3.1.3
    depends_on:
      - postgres
    container_name: metastore
    hostname: metastore
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: >
        -Xmx1G
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=password
    ports:
      - "9083:9083"
    volumes:
      - warehouse:/opt/hive/data/warehouse
      - ./postgresql-42.5.0.jar:/opt/hive/lib/postgres.jar
    networks:
      - bigdata

  # HiveServer2
  hiveserver2:
    image: apache/hive:3.1.3
    depends_on:
      - metastore
    container_name: hiveserver2
    hostname: hiveserver2
    environment:
      SERVICE_NAME: hiveserver2
      SERVICE_OPTS: >
        -Xmx1G
        -Dhive.metastore.uris=thrift://metastore:9083
    ports:
      - "10000:10000"
    volumes:
      - warehouse:/opt/hive/data/warehouse
    networks:
      - bigdata

  # Superset
  superset:
    image: apache/superset
    container_name: superset
    restart: unless-stopped
    ports:
      - "8089:8088"
    environment:
      SUPERSET_SECRET_KEY: 'thisISaSECRET_key'
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      ADMIN_FIRST_NAME: Admin
      ADMIN_LAST_NAME: User
      ADMIN_EMAIL: admin@example.com
    volumes:
      - superset_home:/app/superset_home
    depends_on:
      - hiveserver2
    command: >
      /bin/sh -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Admin --lastname User --email admin@example.com --password admin &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088
      "
    networks:
      - bigdata

  # Cassandra Cluster
  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node1
      - CASSANDRA_LISTEN_ADDRESS=cassandra-node1
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    networks:
      - bigdata

  cassandra-node2:
    image: cassandra:latest
    container_name: cassandra-node2
    depends_on:
      - cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node2
      - CASSANDRA_LISTEN_ADDRESS=cassandra-node2
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    networks:
      - bigdata

  cassandra-node3:
    image: cassandra:latest
    container_name: cassandra-node3
    depends_on:
      - cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=my_cluster
      - CASSANDRA_SEEDS=cassandra-node1
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-node3
      - CASSANDRA_LISTEN_ADDRESS=cassandra-node3
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
    networks:
      - bigdata

volumes:
  hive-db:
  warehouse:
  superset_home:

networks:
  bigdata:
    driver: bridge
